### ISSUE TITLE
Display in aeromodeling club

### ISSUE THREAD

**Issue by evilstarksai** [Shreyasi2002/CS253_Project#33]
Aeromodelling club has a bug in display of image

**Comment by Shreyasi2002** [comment]
@evilstarksai  will you be a little more specific about this issue ....

**Comment by Shreyasi2002** [comment]
@evilstarksai 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/75871525/163727302-17cd1fe9-df62-4794-8f2c-01bf32a35d92.gif)

Can you note down where you are getting a bug ...

**Comment by evilstarksai** [comment]
@Shreyasi2002 it is in the background image.
![Screenshot from 2022-04-18 00-05-13](https://user-images.githubusercontent.com/69984051/163727881-e9e54b23-8950-4737-85cd-8e02954a1f7c.png)

**Comment by Shreyasi2002** [comment]
@evilstarksai  I think the background image is not being rendered properly on your side. It is working fine on our side.
