### ISSUE TITLE
Explore buttons in Festivals page

### ISSUE THREAD

**Issue by deesariganesh18** [Shreyasi2002/CS253_Project#34]
When we click on the explore buttons its again redirects to the same page.

**Comment by deesariganesh18** [comment]
Same for remaining discover and explore club buttons

**Comment by Shreyasi2002** [comment]
Since there are a large number of clubs at IITK, we had only created 2 pages to show the template of any club/festival page. So, we made the buttons redirect to the same page and/or made them disabled.
