### ISSUE TITLE
Error in signup option

### ISSUE THREAD

**Issue by evilstarksai** [Shreyasi2002/CS253_Project#35]
Giving a new user(tried with different usernames) is giving error as "kindly recheck your credentials". It is showing the same error even on changing the other fields. A new user is unable to sign in.
![Screenshot from 2022-04-17 23-46-22](https://user-images.githubusercontent.com/69984051/163727380-6cec8410-4ba6-4b75-9cd8-53826a9e0437.png)

**Comment by Shreyasi2002** [comment]
@evilstarksai We have added the security option that only IITK users can create an account. And since the username and email address should be the same, it will show an error in your case.

If your username is *gsrujith*, the email address should be *gsrujith@iitk.ac.in*

**Comment by evilstarksai** [comment]
@Shreyasi2002, ok. Also mention which credential is causing problem in the signup instead of "Kindly recheck your credentials".
